### ISSUE TITLE
CSS url() statement and source maps

### ISSUE THREAD

**Issue by ValentinGot** [groupe-sii/generator-webpack-angular#6]
URL statement is not working if css-loader sourceMaps are activated.

```css
body {
  background-image: url('/assets/images/an-image.jpg');
}
```

Related style-loader issue: https://github.com/webpack-contrib/style-loader/issues/55
